import type { Lang } from "./lang";

/**
 * UI chrome — lesson commentary is loaded from `data/{lang}/lessons/`.
 * Chess terms follow standard FR usage (coup, partie, trait, ouverture, Blancs/Noirs, etc.).
 */
const EN = {
  brand: "Move by Move",
  headline: "Every move explained",
  landingLead:
    "Chernev’s 1957 classic and Nunn’s modern grandmaster sequel — 63 complete games where each move gets a reason, not a variation dump. Read the author’s note — or listen to it — see the position on the board, then try the next move yourself.",
  landingLeadShort:
    "Chernev and Nunn — 63 games where every move gets a reason. Read it, or listen, with the board in sync.",
  pointChernevTitle: "Chernev · 33 games",
  pointChernevBody:
    "Capablanca, Tarrasch, Rubinstein — development, king safety, and when to attack, told in plain English for players still building intuition.",
  pointNunnTitle: "Nunn · 30 games",
  pointNunnBody:
    "Kasparov, Kramnik, Shirov, Polgar — the same move-by-move habit, updated for how strong players think now.",
  pointBoardTitle: "Board in sync",
  pointBoardBody:
    "Step through commentary with a live diagram, tap Listen for chess-aware speech, and optionally quiz yourself on a Chessnut board with no LED spoilers.",
  openLibrary: "Open the library",
  continue: "Continue",
  continueStudying: "Continue studying",
  reviewLastGame: "Review last game",
  slideCover: "Cover art",
  slideLesson: "Study a game",
  slideCommentary: "Chernev explains",
  productPreview: "Product preview",
  choosePreview: "Choose preview",
  slideLessonAlt:
    "Lesson view: board with knight path arrow, evaluation, best line, and move controls on 12.Nd2",
  slideCommentaryAlt:
    "Commentary panel for 12.Nd2 with takeaway, Listen and Follow controls, and Chernev’s annotation",

  about: "← About",
  settings: "Settings",
  coachEyebrow: "Move-by-Move Coach",
  libraryHeadline: "Study classic games move by move",
  libraryLead:
    "Chernev and Nunn, {n} games — synced board, commentary, Stockfish, and AI analysis prompts.",
  books: "Books",
  games: "Games",
  completed: "Completed",
  inProgress: "In progress",
  continueWhereLeft: "Continue where you left off",
  complete: "complete",
  resume: "Resume →",
  browseGames: "Browse games →",
  backLibrary: "← Library",
  backGames: "← Games",
  finishedOpenReview: "Finished — open to review",
  moveOf: "Move {x} of {y}",
  openings: "Openings",
  ratedPlayers: "Rated players",
  gameIndex: "Game index",
  searchGames: "Search players, openings, events…",
  noGamesMatch: "No games match “{q}”.",
  players: "Players",
  result: "Result",
  estElo: "Est. Elo",
  opening: "Opening",
  progress: "Progress",
  notStarted: "Not started",
  loadingLibrary: "Loading library…",
  bookNotFound: "Book not found.",
  annotatedGames: "{n} annotated games",
  selectedFromBoth: "{n} selected games from Chernev & Nunn",
  gamesRange: "Games {range}",
  moreIntentions: "+{n} more intentions",
  completeStarted: "{done} complete · {started} started",

  gameN: "Game {n}",
  moveProgress: "Move {x} / {y}",
  vs: "vs",
  intention: "Intention",
  openingIdea: "Opening idea",
  loadingLesson: "Loading lesson…",
  chessUpHint:
    "Assistance lights on (unofficial) — green = book move, yellow = destination.",

  settingsLead: "Tune how commentary is read aloud, and connect a Chessnut board.",
  commentary: "Commentary",
  listen: "Listen",
  voice: "Voice",
  recommended: "· recommended",
  speed: "Speed",
  slower: "Slower",
  normal: "Normal",
  faster: "Faster",
  previewVoice: "Preview voice",
  stopPreview: "Stop preview",
  speechUnavailable: "Speech is not available in this browser.",
  loadingVoices: "Loading voices…",
  hardware: "Hardware",
  chessnutBoard: "Chessnut board",
  chessUpBoard: "ChessUp board",
  chessnutCopy:
    "Connect over Bluetooth or USB. Run the LED ballet to verify every square lights cleanly.",
  ledBallet: "LED ballet",
  ledBalletCopy: "Breath, diagonal wave, then a spiral across all 64 squares.",
  runLedBallet: "Run LED ballet",
  dancing: "Dancing…",
  stop: "Stop",
  frameProgress: "Frame {x} / {y}",
  boardReadyBallet: "Board ready — try the LED ballet below.",
  listenOnlyBoard: "Listen-only connection — LEDs are not available on this link.",
  versionLabel: "Move by Move · v{version}",
  language: "Language",
  languageEn: "English",
  languageFr: "Français",
  languageHint: "UI and lesson commentary language. Missing French lessons fall back to English.",

  explains: "{name} explains",
  introduction: "Introduction",
  moveN: "Move {n}",
  keyMoment: "Key moment",
  annotated: "Annotated",
  follow: "Follow",
  listenThisMove: "Listen to this move",
  stopListening: "Stop listening",
  listenFollow: "Listen to this move and each next move",
  stopFollowing: "Stop following moves",
  thisMove: "This move",
  thisAndNext: "This & next moves",
  stopFollowingShort: "Stop following",
  emptyNote: "{name} does not pause on this move — continue to the next.",
  studyBoard: "Study the position on the board ←",
  choosingReply: "Choosing the reply",
  alternatives: "Alternatives considered",
  played: "Played",

  startingPosition: "Starting position",
  whiteToMove: "White to move",
  blackToMove: "Black to move",
  firstMove: "First move",
  previousMove: "Previous move",
  nextMove: "Next move",
  lastMove: "Last move",
  next: "Next",
  nextNote: "Next note → {label}",
  guessFull: "Guess-the-move before advancing",
  quizBoardFull: "Quiz on the board (hide next move)",
  guessShort: "Guess mode",
  quizBoardShort: "Quiz on board",
  keyboardHint: "← → navigate · Space next",

  yourMove: "Your move",
  onChessnut: "On the Chessnut",
  onScreenBoard: "On the screen board",
  type: "Type",
  check: "Check",
  show: "Show",
  illegalMove: "Illegal move — try again.",
  couldNotParse: "Could not parse that move.",
  correctSame: "Correct — same as {name}!",
  authorPlayed: "{name} played {san} here.",

  moves: "Moves",
  start: "Start",
  preview: "Preview: {label}",
  backToPosition: "Back to position",

  eval: "Eval",
  whiteMovesFirst: "White moves first",
  bestLine: "Best line",
  analyzing: "Analyzing…",
  engineUnavailable: "Engine unavailable",
  runningElo: "Running Est. Elo by move",
  stockfishDepth: "Stockfish depth {n}",
  lucasElo: "Lucas Chess–style performance Elo",

  copyPrompt: "Copy analysis prompt",
  promptCopied: "Prompt copied",
  copyFailed: "Copy failed",

  whiteWon: "White won",
  blackWon: "Black won",
  draw: "Draw",
  gameResult: "Game result",

  useChromeHttps: "Use Chrome/Edge on HTTPS or localhost",
  connecting: "Connecting…",
  bluetooth: "Bluetooth",
  usb: "USB",
  disconnect: "Disconnect",
  waitingBoard: "Waiting for board signal",
  endOfGame: "End of game — board idle",
  resetStart: "Reset start · {n} sq",
  resetToStart: "Reset to starting position",
  matchScreen: "Match screen · {n} sq",
  matchScreenPos: "Match the screen position",
  playSan: "Play {san} · {from}→{to}",
  yourMoveQuiz: "Your move · quiz · {side}",
  white: "White",
  black: "Black",
} as const;

const FR: { [K in keyof typeof EN]: string } = {
  brand: "Move by Move",
  headline: "Chaque coup expliqué",
  landingLead:
    "Le classique de Chernev (1957) et la suite moderne de Nunn — 63 parties complètes où chaque coup a une raison, pas un tas de variantes. Lisez la note de l’auteur — ou écoutez-la —, voyez la position sur l’échiquier, puis jouez le coup suivant vous-même.",
  landingLeadShort:
    "Chernev et Nunn — 63 parties où chaque coup a une raison. Lisez, ou écoutez, avec l’échiquier synchronisé.",
  pointChernevTitle: "Chernev · 33 parties",
  pointChernevBody:
    "Capablanca, Tarrasch, Rubinstein — développement, sécurité du roi et moment d’attaquer, en langage clair pour construire l’intuition.",
  pointNunnTitle: "Nunn · 30 parties",
  pointNunnBody:
    "Kasparov, Kramnik, Shirov, Polgar — la même habitude coup par coup, actualisée pour la pensée des joueurs forts d’aujourd’hui.",
  pointBoardTitle: "Échiquier synchronisé",
  pointBoardBody:
    "Parcourez le commentaire avec un diagramme vivant, touchez Écouter pour une voix qui connaît les échecs, et entraînez-vous éventuellement sur un Chessnut sans spoilers LED.",
  openLibrary: "Ouvrir la bibliothèque",
  continue: "Continuer",
  continueStudying: "Continuer l’étude",
  reviewLastGame: "Revoir la dernière partie",
  slideCover: "Illustration",
  slideLesson: "Étudier une partie",
  slideCommentary: "Chernev explique",
  productPreview: "Aperçu du produit",
  choosePreview: "Choisir l’aperçu",
  slideLessonAlt:
    "Vue leçon : échiquier avec flèche de trajet du cavalier, évaluation, meilleure ligne et commandes sur 12.Nd2",
  slideCommentaryAlt:
    "Panneau de commentaire pour 12.Nd2 avec l’idée clé, boutons Écouter et Suivre, et l’annotation de Chernev",

  about: "← À propos",
  settings: "Réglages",
  coachEyebrow: "Coach Move-by-Move",
  libraryHeadline: "Étudiez les classiques coup par coup",
  libraryLead:
    "Chernev et Nunn, {n} parties — échiquier synchronisé, commentaires, Stockfish et prompts d’analyse IA.",
  books: "Livres",
  games: "Parties",
  completed: "Terminées",
  inProgress: "En cours",
  continueWhereLeft: "Reprendre où vous en étiez",
  complete: "terminée",
  resume: "Reprendre →",
  browseGames: "Parcourir les parties →",
  backLibrary: "← Bibliothèque",
  backGames: "← Parties",
  finishedOpenReview: "Terminée — ouvrir pour revoir",
  moveOf: "Coup {x} sur {y}",
  openings: "Ouvertures",
  ratedPlayers: "Joueurs cotés",
  gameIndex: "Index des parties",
  searchGames: "Chercher joueurs, ouvertures, événements…",
  noGamesMatch: "Aucune partie ne correspond à « {q} ».",
  players: "Joueurs",
  result: "Résultat",
  estElo: "Elo estimé",
  opening: "Ouverture",
  progress: "Progression",
  notStarted: "Non commencée",
  loadingLibrary: "Chargement de la bibliothèque…",
  bookNotFound: "Livre introuvable.",
  annotatedGames: "{n} parties annotées",
  selectedFromBoth: "{n} parties choisies chez Chernev & Nunn",
  gamesRange: "Parties {range}",
  moreIntentions: "+{n} intentions de plus",
  completeStarted: "{done} terminées · {started} commencées",

  gameN: "Partie {n}",
  moveProgress: "Coup {x} / {y}",
  vs: "contre",
  intention: "Intention",
  openingIdea: "Idée d’ouverture",
  loadingLesson: "Chargement de la leçon…",
  chessUpHint:
    "LEDs d’assistance (non officiel) — vert = coup du livre, jaune = case d’arrivée.",

  settingsLead: "Réglez la lecture à voix haute du commentaire et branchez un échiquier Chessnut.",
  commentary: "Commentaire",
  listen: "Écouter",
  voice: "Voix",
  recommended: "· recommandée",
  speed: "Vitesse",
  slower: "Plus lent",
  normal: "Normal",
  faster: "Plus rapide",
  previewVoice: "Aperçu de la voix",
  stopPreview: "Arrêter l’aperçu",
  speechUnavailable: "La synthèse vocale n’est pas disponible dans ce navigateur.",
  loadingVoices: "Chargement des voix…",
  hardware: "Matériel",
  chessnutBoard: "Échiquier Chessnut",
  chessUpBoard: "Échiquier ChessUp",
  chessnutCopy:
    "Connexion Bluetooth ou USB. Lancez le ballet LED pour vérifier que chaque case s’allume.",
  ledBallet: "Ballet LED",
  ledBalletCopy: "Souffle, vague en diagonale, puis spirale sur les 64 cases.",
  runLedBallet: "Lancer le ballet LED",
  dancing: "En cours…",
  stop: "Arrêter",
  frameProgress: "Image {x} / {y}",
  boardReadyBallet: "Échiquier prêt — essayez le ballet LED ci-dessous.",
  listenOnlyBoard: "Connexion écoute seule — les LEDs ne sont pas disponibles sur ce lien.",
  versionLabel: "Move by Move · v{version}",
  language: "Langue",
  languageEn: "English",
  languageFr: "Français",
  languageHint: "Langue de l’interface et des commentaires. Les leçons FR manquantes basculent en anglais.",

  explains: "{name} explique",
  introduction: "Introduction",
  moveN: "Coup {n}",
  keyMoment: "Moment clé",
  annotated: "Annoté",
  follow: "Suivre",
  listenThisMove: "Écouter ce coup",
  stopListening: "Arrêter l’écoute",
  listenFollow: "Écouter ce coup et chaque coup suivant",
  stopFollowing: "Arrêter le suivi",
  thisMove: "Ce coup",
  thisAndNext: "Ce coup et les suivants",
  stopFollowingShort: "Arrêter le suivi",
  emptyNote: "{name} ne s’arrête pas sur ce coup — passez au suivant.",
  studyBoard: "Étudiez la position sur l’échiquier ←",
  choosingReply: "Choisir la réponse",
  alternatives: "Alternatives envisagées",
  played: "Joué",

  startingPosition: "Position de départ",
  whiteToMove: "Trait aux Blancs",
  blackToMove: "Trait aux Noirs",
  firstMove: "Premier coup",
  previousMove: "Coup précédent",
  nextMove: "Coup suivant",
  lastMove: "Dernier coup",
  next: "Suivant",
  nextNote: "Note suivante → {label}",
  guessFull: "Devinez le coup avant d’avancer",
  quizBoardFull: "Quiz sur l’échiquier (masquer le coup suivant)",
  guessShort: "Mode guess",
  quizBoardShort: "Quiz échiquier",
  keyboardHint: "← → naviguer · Espace suivant",

  yourMove: "À vous de jouer",
  onChessnut: "Sur le Chessnut",
  onScreenBoard: "Sur l’échiquier à l’écran",
  type: "Saisir",
  check: "Vérifier",
  show: "Montrer",
  illegalMove: "Coup illégal — réessayez.",
  couldNotParse: "Impossible de lire ce coup.",
  correctSame: "Correct — comme {name} !",
  authorPlayed: "{name} a joué {san} ici.",

  moves: "Coups",
  start: "Départ",
  preview: "Aperçu : {label}",
  backToPosition: "Retour à la position",

  eval: "Éval",
  whiteMovesFirst: "Les Blancs jouent en premier",
  bestLine: "Meilleure ligne",
  analyzing: "Analyse…",
  engineUnavailable: "Moteur indisponible",
  runningElo: "Elo estimé cumulé coup par coup",
  stockfishDepth: "Stockfish profondeur {n}",
  lucasElo: "Elo de performance façon Lucas Chess",

  copyPrompt: "Copier le prompt d’analyse",
  promptCopied: "Prompt copié",
  copyFailed: "Échec de la copie",

  whiteWon: "Victoire des Blancs",
  blackWon: "Victoire des Noirs",
  draw: "Partie nulle",
  gameResult: "Résultat de la partie",

  useChromeHttps: "Utilisez Chrome/Edge en HTTPS ou localhost",
  connecting: "Connexion…",
  bluetooth: "Bluetooth",
  usb: "USB",
  disconnect: "Déconnecter",
  waitingBoard: "En attente du signal de l’échiquier",
  endOfGame: "Fin de partie — échiquier au repos",
  resetStart: "Remettre au départ · {n} cases",
  resetToStart: "Revenir à la position de départ",
  matchScreen: "Aligner l’écran · {n} cases",
  matchScreenPos: "Reproduire la position à l’écran",
  playSan: "Jouer {san} · {from}→{to}",
  yourMoveQuiz: "À vous · quiz · {side}",
  white: "Blancs",
  black: "Noirs",
};

export type UiCopy = { readonly [K in keyof typeof EN]: string };

export function ui(lang: Lang): UiCopy {
  return lang === "fr" ? FR : EN;
}

export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(vars[key] ?? ""));
}
